server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://192.168.182.150:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
    #    username: root
    password: ShuShun1558@qq.com
  redis:
    host: 192.168.182.150
    port: 6379
    password: shushun