server:
  port: 8088

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
    #    username: root
    password: 123456
  redis:
    password: shushun
    sentinel:
      master: sue-master
      nodes: 192.168.182.150:26379,192.168.182.151:26379,192.168.182.152:26379
    #Redis 单机实例
#    host: 192.168.182.150
#    port: 6379
#    password: shushun

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl